set (CMAKE_SYSTEM_NAME Linux)

set (TRIPLE "arm-linux-gnueabihf")

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${TRIPLE})
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${TRIPLE})
